### PR TITLE
SDK: add `deployments`

### PR DESCRIPTION
**Pull request by javiermtorres**
## I already...

- [ ] added some tests for any new functionality;
- [ ] updated the documentation.

### CODE REVIEW

**Comment by veekaybee** [comment]
The code looks fine 👍 , but since we're in the process removing `deployments` as an endpoint, I'd suggest we hold off on this one for now because we'll need to remove it.

**Comment by javiermtorres** [comment]
Could you please check https://github.com/mozilla-ai/lumigator/pull/273 then? That one is about integration tests, so it should be mergeable right now. Thanks in advance :)

**Comment by chainlink** [comment]
Can this be closed?

**Comment by javiermtorres** [comment]
I was thinking about either adapting the code to the new jobs endpoint or making it from scratch. Probably starting a new PR is cleaner, so yes, I guess we can close this.

**Pull request closed without merging**
